In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv("C:\\Users\\snehr\\Desktop\\Datasets for pandas (24-05-2024)_files\\placement.csv")

In [6]:
df.head(2)

cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0

In [7]:
df.isnull().sum() 

cgpa            0
resume_score    0
placed          0
dtype: int64

In [8]:
x = df.drop(columns = ['placed'] , axis = 1)  ### Input data 
y = df['placed']   ### Target data 

In [9]:
print("dataframe shape = " , df.shape)
print("Independent data shape = " , x.shape)
print("Dependent data shape = " , y.shape)

dataframe shape =  (100, 3)
Independent data shape =  (100, 2)
Dependent data shape =  (100,)


In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.2 , random_state = 42)

In [12]:
print("dataframe shape = " , df.shape)
print("Independent data shape = " , x.shape)
print("Dependent data shape = " , y.shape)

dataframe shape =  (100, 3)
Independent data shape =  (100, 2)
Dependent data shape =  (100,)


In [13]:
print("X_train  data shape = " , x_train.shape)
print("X_test  data shape = " , x_test.shape)
print("Y_train data shape = " , y_train.shape)
print("Y_test data shape = " , y_test.shape)

X_train  data shape =  (80, 2)
X_test  data shape =  (20, 2)
Y_train data shape =  (80,)
Y_test data shape =  (20,)


In [14]:
np.round(x_train.describe() , 2) 

cgpa  resume_score
count  80.00         80.00
mean    6.95          7.00
std     1.13          1.01
min     5.27          4.95
25%     6.00          6.28
50%     6.62          7.15
75%     8.06          7.69
max     9.31          9.06

In [15]:
from sklearn.preprocessing import StandardScaler 

In [16]:
sc = StandardScaler() 

In [17]:
x_train_sc = sc.fit_transform(x_train)   #### fit means learns the parameters and transform means apply on data 

In [18]:
x_train_new = pd.DataFrame(x_train_sc , columns = x_train.columns) 

In [19]:
x_train_new.head(3)

cgpa  resume_score
0 -0.008602     -0.128926
1  1.001293     -0.925381
2 -0.607389     -0.527154

In [20]:
np.round(x_train_new.describe() , 2) 

cgpa  resume_score
count  80.00         80.00
mean   -0.00         -0.00
std     1.01          1.01
min    -1.50         -2.04
25%    -0.85         -0.72
50%    -0.29          0.15
75%     0.99          0.69
max     2.11          2.05

# Normalization `

In [21]:
from sklearn.preprocessing import MinMaxScaler 

In [22]:
mn = MinMaxScaler() 

In [23]:
x_train_mn = mn.fit_transform(x_train)   ## fit means learn the psrameter and trasnform means apply on data 

In [24]:
x_train_new  = pd.DataFrame(x_train_mn , columns = x_train.columns) 

In [25]:
np.round(x_train_new.describe() , 2)

cgpa  resume_score
count  80.00         80.00
mean    0.42          0.50
std     0.28          0.25
min     0.00          0.00
25%     0.18          0.32
50%     0.33          0.54
75%     0.69          0.67
max     1.00          1.00

# Encoding ===> Convert categorical data into numerical data . 

# Gender ===> Male(0) , Female(1) 

# Grade ===> A(0) , B(1) , C(2)

In [26]:

# (1). LabelEncoding ==> Single data .. 

In [27]:
df = pd.read_csv("C:\\Users\\snehr\\Desktop\\python\\covid_toy.csv")

In [28]:
df.head(3) 

age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [29]:
df.isnull().sum() 

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [30]:
df = df.dropna() 

In [31]:
from sklearn.preprocessing import LabelEncoder 

In [32]:
lb = LabelEncoder() 

In [33]:
df['gender'] = lb.fit_transform(df['gender'])
df['cough'] = lb.fit_transform(df['cough'])
df['city'] = lb.fit_transform(df['city'])
df['has_covid'] = lb.fit_transform(df['has_covid'])

In [34]:
df.head(4) 

age  gender  fever  cough  city  has_covid
0   60       1  103.0      0     2          0
1   27       1  100.0      0     1          1
2   42       1  101.0      0     1          0
3   31       0   98.0      0     2          0

In [35]:
x = df.drop(columns = ['has_covid'] )

y = df['has_covid']

In [36]:
from sklearn.model_selection import train_test_split 

In [37]:
x_train , x_test , y_train, y_test = train_test_split(x,y,test_size = 0.2 , random_state = 42)

In [38]:
from sklearn.preprocessing import MinMaxScaler

In [39]:
mn = MinMaxScaler() 

In [40]:
x_train_mn = mn.fit_transform(x_train)

In [41]:
x_train_new = pd.DataFrame(x_train_mn , columns = x_train.columns) 

In [42]:
x_train_new

age  gender     fever  cough      city
0   0.564103     0.0  0.166667    1.0  0.000000
1   0.807692     0.0  0.500000    1.0  0.333333
2   0.769231     1.0  0.166667    0.0  0.333333
3   0.038462     0.0  0.500000    0.0  0.666667
4   0.820513     0.0  0.000000    1.0  1.000000
..       ...     ...       ...    ...       ...
67  0.102564     0.0  0.333333    1.0  0.666667
68  0.628205     0.0  1.000000    1.0  0.666667
69  0.551282     0.0  0.833333    0.0  0.666667
70  0.448718     0.0  0.000000    1.0  0.333333
71  0.012821     0.0  1.000000    0.0  0.666667

[72 rows x 5 columns]

In [43]:
np.round(x_train_new.describe() , 1) 

age  gender  fever  cough  city
count  72.0    72.0   72.0   72.0  72.0
mean    0.5     0.4    0.5    0.3   0.4
std     0.3     0.5    0.4    0.5   0.3
min     0.0     0.0    0.0    0.0   0.0
25%     0.2     0.0    0.2    0.0   0.0
50%     0.5     0.0    0.5    0.0   0.3
75%     0.8     1.0    0.7    1.0   0.7
max     1.0     1.0    1.0    1.0   1.0

# Ordinal Encoder===> Multi - Categorical data encode 

In [44]:
import numpy as  np
import pandas as pd

In [45]:
df = pd.read_csv("C:\\Users\\snehr\\Desktop\\python\\covid_toy.csv")

In [46]:
df.head(2)


age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [47]:
df = df.dropna()

In [48]:
from sklearn.preprocessing import OrdinalEncoder

In [49]:
df = df.drop(columns = ['age' , 'fever'])

In [50]:
df

gender   cough       city has_covid
0     Male    Mild    Kolkata        No
1     Male    Mild      Delhi       Yes
2     Male    Mild      Delhi        No
3   Female    Mild    Kolkata        No
4   Female    Mild     Mumbai        No
..     ...     ...        ...       ...
95  Female    Mild  Bangalore        No
96  Female  Strong    Kolkata       Yes
97  Female    Mild  Bangalore        No
98  Female  Strong     Mumbai        No
99  Female  Strong    Kolkata       Yes

[90 rows x 4 columns]

In [51]:
df['gender'].value_counts()

gender
Female    54
Male      36
Name: count, dtype: int64

In [52]:
df['cough'].value_counts()

cough
Mild      57
Strong    33
Name: count, dtype: int64

In [53]:
df['city'].value_counts()

city
Kolkata      29
Bangalore    28
Delhi        20
Mumbai       13
Name: count, dtype: int64

In [54]:
df['has_covid'].value_counts()

has_covid
No     52
Yes    38
Name: count, dtype: int64

In [55]:
oe = OrdinalEncoder(categories=[['Male' , 'Female'],['Mild' , 'Strong'] , 
                                ['Kolkata' , 'Bangalore' , 'Delhi' , 'Mumbai'], ['No' , 'Yes']])

In [56]:
df.head(3)

gender cough     city has_covid
0   Male  Mild  Kolkata        No
1   Male  Mild    Delhi       Yes
2   Male  Mild    Delhi        No

In [57]:
oe

OrdinalEncoder(categories=[['Male', 'Female'], ['Mild', 'Strong'],
                           ['Kolkata', 'Bangalore', 'Delhi', 'Mumbai'],
                           ['No', 'Yes']])

In [58]:
oe.fit(df)

OrdinalEncoder(categories=[['Male', 'Female'], ['Mild', 'Strong'],
                           ['Kolkata', 'Bangalore', 'Delhi', 'Mumbai'],
                           ['No', 'Yes']])

In [59]:
df_new = oe.transform(df) 

In [60]:
df_new = pd.DataFrame(df_new , columns = ['gender' , 'cough' , 'city' , 'has_covid'])

In [61]:
df_new

gender  cough  city  has_covid
0      0.0    0.0   0.0        0.0
1      0.0    0.0   2.0        1.0
2      0.0    0.0   2.0        0.0
3      1.0    0.0   0.0        0.0
4      1.0    0.0   3.0        0.0
..     ...    ...   ...        ...
85     1.0    0.0   1.0        0.0
86     1.0    1.0   0.0        1.0
87     1.0    0.0   1.0        0.0
88     1.0    1.0   3.0        0.0
89     1.0    1.0   0.0        1.0

[90 rows x 4 columns]

In [62]:
from sklearn.preprocessing import StandardScaler 

In [63]:
sc = StandardScaler() 

In [64]:
df_sc = sc.fit_transform(df_new)

In [65]:
df_new_sc= pd.DataFrame(df_sc , columns = df_new.columns) 

In [66]:
np.round(df_new_sc.describe() , 2)

gender  cough   city  has_covid
count   90.00  90.00  90.00      90.00
mean     0.00   0.00   0.00      -0.00
std      1.01   1.01   1.01       1.01
min     -1.22  -0.76  -1.14      -0.85
25%     -1.22  -0.76  -1.14      -0.85
50%      0.82  -0.76  -0.18      -0.85
75%      0.82   1.31   0.78       1.17
max      0.82   1.31   1.74       1.17

# OneHotEncoder ===> for multi demension data

In [67]:
df = pd.read_csv("C:\\Users\\snehr\\Desktop\\python\\covid_toy.csv")

In [68]:
df.head(2)

age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [69]:
df = df.dropna()

In [70]:
df = df.drop(columns = ['age', 'fever'])

In [71]:
df

gender   cough       city has_covid
0     Male    Mild    Kolkata        No
1     Male    Mild      Delhi       Yes
2     Male    Mild      Delhi        No
3   Female    Mild    Kolkata        No
4   Female    Mild     Mumbai        No
..     ...     ...        ...       ...
95  Female    Mild  Bangalore        No
96  Female  Strong    Kolkata       Yes
97  Female    Mild  Bangalore        No
98  Female  Strong     Mumbai        No
99  Female  Strong    Kolkata       Yes

[90 rows x 4 columns]

In [72]:
# gender ===> Male , Female 

In [73]:
from sklearn.preprocessing import OneHotEncoder

In [74]:
ohe = OneHotEncoder(drop =  'first' ,  sparse = False , dtype = np.int32)

In [75]:
df_new = ohe.fit_transform(df[['gender' , 'cough', 'city' ,'has_covid']])

C:\Users\snehr\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [76]:
df_new

array([[1, 0, 0, 1, 0, 0],
       [1, 0, 1, 0, 0, 1],
       [1, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [1, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 1],
       [0, 1, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0],
       [1, 1, 0, 1, 0, 1],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 1],
       [0, 1, 0, 1, 0, 1],
       [0, 0, 1, 0, 0, 1],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 1, 0, 0, 0],
       [1, 0, 0, 1, 0, 0],
       [1, 0, 1, 0, 0, 1],
       [1, 0, 0, 1, 0, 0],
       [0, 1, 1, 0, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 1],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [1, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 1],
 

In [77]:
df.shape

(90, 4)

In [78]:
df_new.shape

(90, 6)

In [79]:
df = pd.read_csv("C:\\Users\\snehr\\Desktop\\python\\tips.csv")

In [80]:
df.head(2)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [81]:
df = df.dropna()

In [82]:
df = df.drop(columns = ['total_bill' , 'tip' , 'size'])
df

sex smoker   day    time
0    Female     No   Sun  Dinner
1      Male     No   Sun  Dinner
2      Male     No   Sun  Dinner
3      Male     No   Sun  Dinner
4    Female     No   Sun  Dinner
..      ...    ...   ...     ...
239    Male     No   Sat  Dinner
240  Female    Yes   Sat  Dinner
241    Male    Yes   Sat  Dinner
242    Male     No   Sat  Dinner
243  Female     No  Thur  Dinner

[244 rows x 4 columns]

In [83]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [84]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [85]:
oe = OrdinalEncoder(categories =[['Female' , 'Male'] , ['No' , 'Yes'] ,
                                 ['Sat' , 'Sun' , 'Thur' , 'Fri'] , ['Dinner' , 'Lunch']])

In [86]:
oe

OrdinalEncoder(categories=[['Female', 'Male'], ['No', 'Yes'],
                           ['Sat', 'Sun', 'Thur', 'Fri'], ['Dinner', 'Lunch']])

In [87]:
oe.fit(df)

OrdinalEncoder(categories=[['Female', 'Male'], ['No', 'Yes'],
                           ['Sat', 'Sun', 'Thur', 'Fri'], ['Dinner', 'Lunch']])

In [88]:
df_ordinal = oe.transform(df)

In [89]:
df_ordinal

array([[0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],


In [90]:
ohe = OneHotEncoder(drop = 'first' , sparse = False , dtype = np.int32) 

In [91]:
df_new = ohe.fit_transform(df[['sex' , 'smoker' , 'day' , 'time']]) 

C:\Users\snehr\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [92]:
df_new

array([[0, 0, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 0],
       ...,
       [1, 1, 1, 0, 0, 0],
       [1, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0]])