# What is function transformer . 

# The function transformer is a tool in scikit-learn , a popular python library for machine learning , that allows you to apply a specified function to the input data. The Function Transformer can be useful for performing custom transformations of input data in a machine pipeline. 

In [4]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

# create a dataset
x = np.array([[1,2], [3,4]])

# definer the transformation function
log_transform = FunctionTransformer(np.log1p)

# apply the transformation to the dataset 
x_transformed = log_transform.transform(x)

# view the transformed data
print(x_transformed)

[[0.69314718 1.09861229]
 [1.38629436 1.60943791]]


In [5]:
# Pratical usecases 

# 1. custom feature Engineering 
from sklearn.preprocessing import FunctionTransformer 
import numpy as np

# create a dataset 
x= np.array([[1,2],[3,4]])

# define a custom feature engineering function 
def my_feature_engineering(x):
    return np.hstack((x,x**2))

# create a functiontransformer to apply the custom function 
custom_transformer = FunctionTransformer(my_feature_engineering)

# apply the transformer to the input data
x_transformed = custom_transformer.transform(x)

# view the transformed data
print(x_transformed)

[[ 1  2  1  4]
 [ 3  4  9 16]]


In [7]:
# 2. Scaling And Normalization 

from sklearn.preprocessing import FunctionTransformer
import numpy as np

# create a dataset 
X = np.array([[1,2],[3,4]])

# define a custom scalling function
def my_scalling(x):
    return X/ np.max(x)

# create a function transformer to apply the custom function 
custom_transformer = FunctionTransformer(my_scalling)

# apply the transformer to the input data
X_transformed = custom_transformer.transform(x)

# view the transform data
print(X_transformed)

[[0.25 0.5 ]
 [0.75 1.  ]]


In [8]:
# 3. Data Cleaning 
from sklearn.preprocessing import FunctionTransformer
import numpy as np

# create a dataset with missing values
X = np.array([[1,2], [3,np.nan]])

# define a custom cleanng function 
def my_cleaning(X):
    X[np.isnan(X)] = 0
    return X

# create a function transformer to apply the custom function
custom_transformer = FunctionTransformer(my_cleaning)

# apply the transformert to the input data
X_transformed = custom_transformer.transform(X)

# view the transform data
print(X_transformed)

[[1. 2.]
 [3. 0.]]


In [1]:
# 4. Dimensionality reduction 


