# Models ===> Supervised , UnSupervised


# Data Gathering ===> Data Preparation ==> Apply ML Algorithams ===> Performance Evaluation

# Data ==> 
# (1). Numerical ==> Continous===> LinearRegression , DecisionTreeRegressor , RandomForestRegressor

# (2). Categorical ==> Discrete ===> LogisticRegression , DecisionTreeClassifier , RandomForestClassifier

# Model Evaluation Techniques:

# 1.) For Categorical Data: accuracy_score, precision, recall, f2_score
    
# 2.) For Numerical Data: r2_score

# Logic:

2+2=4 (2+2 is x_train, 4 is y_train)

3+2=5 (3+2 is x_train, 5 is y_train)

6+4=? (6+4 is x_test, 9 or 11 is y_pred, 10 is y_test / y_actual)

In [67]:
import numpy as np
import pandas as pd

In [68]:
df = pd.read_csv("C:\\Users\\snehr\\Desktop\\python\\tips.csv")

In [69]:
df.head(2)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [70]:
df = df.dropna()

In [71]:
from sklearn.preprocessing import LabelEncoder

In [72]:
lb = LabelEncoder()

In [73]:
df['sex'] = lb.fit_transform(df['sex'])
df['smoker'] = lb.fit_transform(df['smoker'])
df['day'] = lb.fit_transform(df['day'])
df['time'] = lb.fit_transform(df['time'])

In [74]:
df.head(3)

total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     0     2
1       10.34  1.66    1       0    2     0     3
2       21.01  3.50    1       0    2     0     3

In [75]:
x = df.drop(columns = ['total_bill'] , axis = 1) # input data 
y = df['total_bill'] # target data

In [76]:
from sklearn.model_selection import train_test_split

In [77]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.2 , random_state = 42)

In [78]:
from sklearn.linear_model import LinearRegression

In [79]:
lr = LinearRegression()

In [80]:
lr.fit(x_train , y_train)

LinearRegression()

In [81]:
y_pred = lr.predict(x_test)

In [82]:
y_pred  #### Predicted Output

array([18.44568817, 15.26213947, 21.37308696, 33.13666628, 14.95435173,
       18.05035419, 17.38562243, 13.68721997, 18.86008571, 19.64605326,
       18.18729901, 13.44366535, 10.70355724, 18.05035419,  8.61338614,
       13.34950865, 24.65332592, 20.87844579, 15.57564354, 30.90121823,
       21.62808784, 21.99843904, 22.83935236, 13.38516216, 24.70038589,
       13.86611782, 14.4138432 , 25.7645119 , 21.37308696, 36.25951308,
       24.1679323 , 16.14412529, 22.09950165, 21.32165768, 21.91217117,
       20.96823128, 16.0514953 , 29.84077785, 14.36000666, 17.78221463,
       12.80013025, 12.16613701, 16.87097722, 16.55912921, 15.74753309,
       11.00839999, 15.84822105, 18.95627311, 11.32122902])

In [83]:
# y_test ### Actual output

In [84]:
from sklearn.metrics import r2_score

In [85]:
r2_score(y_test, y_pred)

0.6334779105328124

In [86]:
x_test.shape

(49, 6)

In [87]:
y_pred.shape

(49,)

In [88]:
df = pd.read_csv("C:\\Users\\snehr\\Desktop\\python\\covid_toy.csv")

In [89]:
df.head(2)

age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [90]:
df = df.dropna()

In [91]:
from sklearn.preprocessing import LabelEncoder

In [92]:
lb = LabelEncoder()

In [93]:
df['gender'] = lb.fit_transform(df['gender'])
df['cough'] = lb.fit_transform(df['cough'])
df['city'] = lb.fit_transform(df['city'])
df['has_covid'] = lb.fit_transform(df['has_covid'])

In [94]:
df.head(2)

age  gender  fever  cough  city  has_covid
0   60       1  103.0      0     2          0
1   27       1  100.0      0     1          1

In [95]:
df = df.dropna()

In [96]:
x = df.drop(columns = ['has_covid'], axis = 1) # Input Data
y = df['has_covid'] # Target Data

In [97]:
from sklearn.model_selection import train_test_split

In [98]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 42)

In [99]:
from sklearn.linear_model import LogisticRegression

In [100]:
lr = LogisticRegression()

In [101]:
lr.fit(x_train, y_train)

LogisticRegression()

In [102]:
from sklearn.metrics import accuracy_score

In [103]:
y_pred = lr.predict(x_test)

In [104]:
y_pred # Predicted Output

array([0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

In [105]:
# y_test # Actual Output

In [106]:
accuracy_score(y_test , y_pred)

0.4444444444444444

In [107]:
from sklearn.metrics import accuracy_score

In [108]:
accuracy_score(y_test, y_pred)

0.4444444444444444

In [109]:
# from sklearn.preprocessing import StandardScaler

In [110]:
# sc = StandardScaler()

In [111]:
# x_train_new = sc.fit_transform(x_train)
# x_test_new = sc.fit_transform(x_test)

In [112]:
# lr.fit(x_train_new, y_train)

In [113]:
# y_pred = lr.predict(x_test_new)

In [114]:
# accuracy_score(y_test, y_pred)

In [115]:
df = pd.read_csv("C:\\Users\\snehr\\Desktop\\python\\social_network_ads.csv")

In [116]:
df.head(2)

User ID Gender  Age  EstimatedSalary  Purchased
0  15624510   Male   19            19000          0
1  15810944   Male   35            20000          0

In [117]:
df = df.dropna()

In [118]:
from sklearn.preprocessing import LabelEncoder

In [119]:
lb = LabelEncoder()

In [120]:
df['Gender'] = lb.fit_transform(df['Gender'])

In [121]:
df.head(3)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       1   19            19000          0
1  15810944       1   35            20000          0
2  15668575       0   26            43000          0

In [122]:
x = df.drop(columns = ['Purchased'], axis = 1) # Input Data
y = df['Purchased'] # Target Data

In [123]:
from sklearn.model_selection import train_test_split

In [124]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 42)

In [125]:
from sklearn.linear_model import LogisticRegression

In [126]:
lr = LogisticRegression()

In [129]:
y_pred = lr.predict(x_test)

NotFittedError: This LogisticRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [61]:
lr.fit(x_train, y_train)

LogisticRegression()

In [62]:
y_pred = lr.predict(x_test)

In [63]:
y_pred # Predicted Output

array([0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

In [64]:
# y_test # Actual Output

In [65]:
from sklearn.metrics import accuracy_score

In [66]:
accuracy_score(y_test, y_pred)

0.4444444444444444