In [1]:
# Numpy ===> 

# (1). same data type 
# (2). Memory consume less 
# (3). Computation Power 

In [2]:
import numpy as np 

In [3]:
a = [1,23,455,90]
type(a) 

list

In [4]:
b = np.array(a) 
b

array([  1,  23, 455,  90])

In [5]:
type(b) 

numpy.ndarray

In [8]:
a = [] 
size = int(input("Enter size:"))
for i in range(size):
    val = int(input("Enter item:"))
    a.append(val) 
b = np.array(a) 
b

Enter size: 3
Enter item: 45
Enter item: 56
Enter item: 89


array([45, 56, 89])

In [ ]:
how can we check shape and size of an array


In [9]:
a = np.array([1,34,89,9900])

In [10]:
a

array([   1,   34,   89, 9900])

In [11]:
print("Total Shape = " , a.shape)
print("Total Elements = " , a.size)

Total Shape =  (4,)
Total Elements =  4


In [12]:
a = [[1,2,3] , [4,5,6] , [7,8,9]]
b = np.array(a) 
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
# row_1 = [1,2,3]
# row_2 = [4,5,6]
# row_3 = [7,8,9]

# col_1 = [1,4,7]
# copl_2 = [2,5,8]
# col_3 = [3,6,9]

In [14]:
print("Total Shape = " , b.shape)
print("Total Elements = " , b.size)

Total Shape =  (3, 3)
Total Elements =  9


In [15]:
# iMAGES ===> pixels(0-255) ===> 0px black , 255 px white ==> Normalize(0-1)px 

# Intially weights ===> 0 , 1 


# optimization ===> 0,1 


# matrix ===> n(rows) , n(columns) 

# symmatric Matrix ===> n(rows) = n(columns) 

# Aymmatric Matrix ===> n(rows) !=n(columns) 

# [(1,1) , (2,2) , (3,3) , (4,4)......(n,n)]

In [ ]:
prer- define functions

(1) zeros () ==> it will create an array in which all the elements are 0. 


In [18]:
a = np.zeros(4)
a

array([0., 0., 0., 0.])

In [19]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
(2) ones ()==> it will create an array in which all the elements are 1.  

In [20]:
a = np.ones(3)
a

array([1., 1., 1.])

In [21]:
a = np.ones((2 , 3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
type(a) 

numpy.ndarray

In [23]:
a.shape

(2, 3)

In [24]:
a.size

6

In [ ]:
(3). eye()==> in this function diagonalpositional elements are 1 and rest all zero.

In [25]:
a = np.eye(4)    ####Symmatric Matrix 
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
a = np.eye(3,4)  ####Asymmatric Matrix 
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
4. daig==> this function create a two dimensinal array with all the daigonal elements as the given value and rest zero.


In [21]:
import numpy as np
a = np.diag([1,4,8,9])
a

array([[1, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 9]])

In [ ]:
5. randint==> this function is used to generate a random number between a given range .
syntax  == randint(min_value , max_value , total_numbers) 

In [22]:
import numpy as np 
a = np.random.randint(1,10,3) 
a

array([2, 4, 7])

In [ ]:
6.rand==>this function is used to generate a random number betweenn 0 to 1.
syntax == rand(number of values)

In [23]:
import numpy as np 

a = np.random.rand(5) 
a

array([0.05028956, 0.80430918, 0.34141013, 0.32281872, 0.37636155])

In [ ]:
7. randn()==> this function is used to generate a random number from -3 to close 3. this may return positive or negative numbers as well.
syntax == random.randn(number of values) 

In [24]:
import numpy as np 
a = np.random.randn(5) 
a

array([-1.16322954,  1.141769  ,  0.78130091, -1.05502703,  1.52140958])

In [10]:
#reshaping data 

In [25]:
import numpy as np 

a = np.random.randint(1,50,12) 
a

array([16, 30, 11, 30,  5, 22, 41, 45,  3, 31, 40, 38])

In [13]:
#n(rows)* n(columns)=n(total_elements)

In [26]:
a.shape 

(12,)

In [27]:
a = a.reshape(2,6) 
a

array([[16, 30, 11, 30,  5, 22],
       [41, 45,  3, 31, 40, 38]])

In [28]:
a = a.reshape(6,2) 
a

array([[16, 30],
       [11, 30],
       [ 5, 22],
       [41, 45],
       [ 3, 31],
       [40, 38]])

In [29]:
a = a.reshape(3,4) 
a

array([[16, 30, 11, 30],
       [ 5, 22, 41, 45],
       [ 3, 31, 40, 38]])

In [30]:
a = a.reshape(4,3) 
a

array([[16, 30, 11],
       [30,  5, 22],
       [41, 45,  3],
       [31, 40, 38]])

In [31]:
a = a.reshape(12,1) 
a

array([[16],
       [30],
       [11],
       [30],
       [ 5],
       [22],
       [41],
       [45],
       [ 3],
       [31],
       [40],
       [38]])

In [16]:
# principal of -1

In [32]:
a= a.reshape(-1 , 4)
a

array([[16, 30, 11, 30],
       [ 5, 22, 41, 45],
       [ 3, 31, 40, 38]])

In [ ]:
# Seed Function ()  ==> We know that randint function generates random numbers . Everytime we run the program  , new set of random number is generated . So , solve this problem we will use seed function . 

In [33]:
import numpy as np 

np.random.seed(5) 
a = np.random.randint(1,100 , 10) 
a

array([79, 62, 17, 74,  9, 63, 28, 31, 81,  8])

In [34]:
#### np.random.seed(111) 
a = np.random.randint(1,500,30).reshape(6,5) 
a

array([[205, 400, 114, 438, 488],
       [ 81,  28,  45, 206, 204],
       [ 66, 432,  31, 469,  87],
       [126, 147, 255, 378, 138],
       [363,  42, 490, 447, 386],
       [211, 104, 145, 463,   6]])

In [ ]:
# View Vs Copy ==> When we slice a sub-array from an array , it may be done by two ways . 

In [35]:
import numpy as np 
a = np.array([10 , 20 , 30 , 40 , 50 , 60 , 70 , 80 ])
b = a[3:6] 
b[:] = 0 
a

array([10, 20, 30,  0,  0,  0, 70, 80])

In [ ]:
# copy 

In [36]:
a = np.array([10 , 20 , 30 , 40 , 50 , 60 , 70 , 80 ])
b = a[3:6].copy() 
b[:] = 0 
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [37]:
b

array([0, 0, 0])

In [ ]:
condition selection 

In [38]:
import numpy as np 
a = np.arange(1,16) 
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [39]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [40]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [41]:
b = a>10 
a[b]

array([11, 12, 13, 14, 15])

In [42]:
a[a%2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [ ]:
operations on array 

In [43]:
import numpy as np 
a = np.arange(1,5) 
a*2

array([2, 4, 6, 8])

In [44]:
a+2 

array([3, 4, 5, 6])

In [45]:
a**2

array([ 1,  4,  9, 16])

In [46]:
a  = np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [47]:
b = np.array([5,6,7,8]).reshape(2,2) 
b

array([[5, 6],
       [7, 8]])

In [48]:
a+b 

array([[ 6,  8],
       [10, 12]])

In [49]:
b-a

array([[4, 4],
       [4, 4]])

In [52]:
b/a

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [51]:
a*b

array([[ 5, 12],
       [21, 32]])

In [53]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [ ]:
some more important numpy functions

In [54]:
import  numpy as np 
a = np.array([10,20,30,40,50]) 
np.min(a) 

10

In [55]:
np.max(a)   #it will return maximum value of the array 

50

In [56]:
np.argmin(a)  #it will return indexing of minimum value

0

In [57]:
np.argmax(a)   # it will return indexing of maximum value 

4

In [72]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [58]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [ ]:
linspace()==> this function returns value between a given range and with a same gap between consicutive elements.

In [59]:
import numpy as np 

a = np.linspace(1,2,5) 
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [60]:
import numpy as np 

np.random.seed(122) 
a = np.random.randint(1,21,9).reshape(3,3) 
a

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [61]:
np.sum(a) 

116

In [62]:
np.sum(a , axis = 1) 

array([40, 46, 30])

In [63]:
np.min(a) 

3

In [64]:
np.max(a) 

17

In [65]:
np.cumsum(a)

array([ 16,  27,  40,  57,  70,  86,  89, 105, 116])

In [66]:
a

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [ ]:
 np.unique(arr , return_index = True , return_counts = True) 

returns 3 array . 
1 . the array with unique values . 
2 . the array with respective index value . 
3 . the array with counting of frequencey . 

In [67]:
a = np.array([10,20,30,40,10,20,50]) 
np.unique(a , return_index  = True , return_counts = True) 


(array([10, 20, 30, 40, 50]),
 array([0, 1, 2, 3, 6], dtype=int64),
 array([2, 2, 1, 1, 1], dtype=int64))

In [ ]:
# horizontal and vertical stacking

In [68]:

a = np.array([1,2,3,4]) 
b = np.array([5,6,7,8]) 
a

array([1, 2, 3, 4])

In [69]:
b

array([5, 6, 7, 8])

In [70]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [71]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])