In [1]:
import numpy as np


In [2]:
import numpy as np
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(array_1d)


1D Array:
[1 2 3 4 5]


In [1]:
import numpy as np 
a = np.random.randint(1,70,10) 
a


array([28, 22, 61, 17, 25, 47, 20, 17,  7, 17])

In [3]:
import numpy as np
array_10_to_20 = np.arange(10, 21)
print("Array from 10 to 20:")
print(array_10_to_20)


Array from 10 to 20:
[10 11 12 13 14 15 16 17 18 19 20]


In [2]:
import  numpy as np 
a = np.array([10,20,30,40,50]) 
np.min(a)

10

In [4]:
import numpy as np
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(array_1d)


[1 2 3 4 5 6 7 8 9]


In [3]:
import numpy as np 
a = np.random.randn(3*3) 
a

array([ 0.09373263,  1.29923581,  0.95946347, -0.41915278,  0.57948988,
       -0.53695521, -0.44217217, -0.67701401, -0.10091976])